### PR TITLE
[WIP] twilioconfig, more redis, package.json for building redis

### PR DESCRIPTION
**Pull request by cpruijsen**

### CODE REVIEW

**Comment by cpruijsen** [comment]
don't worry about merging yet - mainly here for you all to see - the Twilio config change is needed in all your code to make it compile.

**Comment by cpruijsen** [comment]
checks failing has to do with twiliocredentials in travisCI

**Comment by cpruijsen** [comment]
ok fixed Twiliocreds in Travis -- issues now have to do with redisconnection:      `Uncaught Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379` @alexcstark

**Comment by cpruijsen** [comment]
Travis fixed! still need to add some tests using fakeredis - and have a bigger redis update (done on local) to push once that's done :)

**Comment by cpruijsen** [comment]
one test failing - due to localhost endpoint

**Comment by alexcstark** [comment]
Passes

**Pull request merged**
